# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_2(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(950, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.login_label = QtWidgets.QLabel(self.centralwidget)
        self.login_label.setGeometry(QtCore.QRect(340, 20, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.login_label.setFont(font)
        self.login_label.setAlignment(QtCore.Qt.AlignCenter)
        self.login_label.setObjectName("login_label")
        self.username_label = QtWidgets.QLabel(self.centralwidget)
        self.username_label.setGeometry(QtCore.QRect(340, 90, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.username_label.setFont(font)
        self.username_label.setAlignment(QtCore.Qt.AlignCenter)
        self.username_label.setObjectName("username_label")
        self.password_label = QtWidgets.QLabel(self.centralwidget)
        self.password_label.setGeometry(QtCore.QRect(340, 190, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.password_label.setFont(font)
        self.password_label.setAlignment(QtCore.Qt.AlignCenter)
        self.password_label.setObjectName("password_label")
        self.login_button = QtWidgets.QPushButton(self.centralwidget)
        self.login_button.setGeometry(QtCore.QRect(340, 300, 81, 31))
        self.login_button.setObjectName("login_button")
        self.entry_user = QtWidgets.QLineEdit(self.centralwidget)
        self.entry_user.setGeometry(QtCore.QRect(300, 130, 171, 20))
        self.entry_user.setObjectName("entry_user")
        self.entry_password = QtWidgets.QLineEdit(self.centralwidget)
        self.entry_password.setGeometry(QtCore.QRect(300, 240, 171, 20))
        self.entry_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.entry_password.setObjectName("entry_password")
        self.invalid_label = QtWidgets.QLabel(self.centralwidget)
        self.invalid_label.setGeometry(QtCore.QRect(310, 270, 151, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.invalid_label.setFont(font)
        self.invalid_label.setMouseTracking(False)
        self.invalid_label.setAlignment(QtCore.Qt.AlignCenter)
        self.invalid_label.setObjectName("invalid_label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.login_label.setText(_translate("MainWindow", "LOGIN"))
        self.username_label.setText(_translate("MainWindow", "Username"))
        self.password_label.setText(_translate("MainWindow", "Password"))
        self.login_button.setText(_translate("MainWindow", "LOGIN"))
        self.invalid_label.setText(_translate("MainWindow", ""))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_2()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
