# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signup_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_3(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(950, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(300, 140, 291, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.user_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.user_label.setFont(font)
        self.user_label.setAlignment(QtCore.Qt.AlignCenter)
        self.user_label.setObjectName("user_label")
        self.verticalLayout.addWidget(self.user_label)
        self.user_entry = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.user_entry.setInputMask("")
        self.user_entry.setText("")
        self.user_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.user_entry.setObjectName("user_entry")
        self.verticalLayout.addWidget(self.user_entry)
        self.pass_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.pass_label.setAlignment(QtCore.Qt.AlignCenter)
        self.pass_label.setObjectName("pass_label")
        self.verticalLayout.addWidget(self.pass_label)
        self.pass_entry = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.pass_entry.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pass_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.pass_entry.setObjectName("pass_entry")
        self.verticalLayout.addWidget(self.pass_entry)
        self.confirm_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.confirm_label.setAlignment(QtCore.Qt.AlignCenter)
        self.confirm_label.setObjectName("confirm_label")
        self.verticalLayout.addWidget(self.confirm_label)
        self.confirm_entry = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.confirm_entry.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirm_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.confirm_entry.setObjectName("confirm_entry")
        self.verticalLayout.addWidget(self.confirm_entry)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(380, 50, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.notification_label = QtWidgets.QLabel(self.centralwidget)
        self.notification_label.setGeometry(QtCore.QRect(305, 410, 281, 20))
        self.notification_label.setText("")
        self.notification_label.setAlignment(QtCore.Qt.AlignCenter)
        self.notification_label.setObjectName("notification_label")
        self.signup_button = QtWidgets.QPushButton(self.centralwidget)
        self.signup_button.setGeometry(QtCore.QRect(380, 430, 131, 41))
        self.signup_button.setObjectName("signup_button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.user_label.setText(_translate("MainWindow", "Username"))
        self.pass_label.setText(_translate("MainWindow", "Password"))
        self.confirm_label.setText(_translate("MainWindow", "Confirm password"))
        self.label_4.setText(_translate("MainWindow", "SIGN UP"))
        self.signup_button.setText(_translate("MainWindow", "Sign up"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_3()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
